/**
 * Fallback data used when the database is empty.
 * Centralized here to avoid duplication across components.
 */

import { Project, Certificate } from "@/lib/types";

export const fallbackProjects: Project[] = [
    {
        id: "1",
        title: "E-Commerce Platform",
        description: "A full-stack e-commerce solution with real-time inventory, AI recommendations, and seamless checkout experience.",
        tags: ["Next.js", "TypeScript", "Stripe", "PostgreSQL"],
        image_url: "https://images.unsplash.com/photo-1661956602116-aa6865609028?w=800&h=600&fit=crop",
        live_url: "#",
        github_url: "#",
        size: "large",
        featured: true,
        display_order: 0,
        created_at: new Date().toISOString(),
    },
    {
        id: "2",
        title: "AI Dashboard",
        description: "Analytics dashboard with ML-powered insights and real-time data visualization.",
        tags: ["React", "Python", "TensorFlow"],
        image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
        live_url: "#",
        github_url: "#",
        size: "medium",
        featured: false,
        display_order: 1,
        created_at: new Date().toISOString(),
    },
    {
        id: "3",
        title: "Social App",
        description: "Real-time social platform with chat, stories, and community features.",
        tags: ["React Native", "Firebase"],
        image_url: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=600&fit=crop",
        live_url: "#",
        github_url: "#",
        size: "small",
        featured: false,
        display_order: 2,
        created_at: new Date().toISOString(),
    },
    {
        id: "4",
        title: "Design System",
        description: "Component library with 50+ accessible components and theming support.",
        tags: ["Storybook", "Figma", "CSS"],
        image_url: "https://images.unsplash.com/photo-1545235617-9465d2a55698?w=800&h=600&fit=crop",
        live_url: "#",
        github_url: "#",
        size: "small",
        featured: false,
        display_order: 3,
        created_at: new Date().toISOString(),
    },
];

export const fallbackCertificates: Certificate[] = [
    {
        id: "1",
        title: "AWS Certified Solutions Architect",
        issuer: "Amazon Web Services",
        date: "2024",
        credential_url: "#",
        image_url: null,
        skills: ["Cloud Architecture", "AWS Services", "Security"],
        featured: true,
        display_order: 0,
        created_at: new Date().toISOString(),
    },
    {
        id: "2",
        title: "Professional Frontend Developer",
        issuer: "Meta",
        date: "2023",
        credential_url: "#",
        image_url: null,
        skills: ["React", "JavaScript", "Web Performance"],
        featured: true,
        display_order: 1,
        created_at: new Date().toISOString(),
    },
    {
        id: "3",
        title: "Full Stack Web Development",
        issuer: "freeCodeCamp",
        date: "2023",
        credential_url: "#",
        image_url: null,
        skills: ["Node.js", "MongoDB", "REST APIs"],
        featured: false,
        display_order: 2,
        created_at: new Date().toISOString(),
    },
    {
        id: "4",
        title: "TypeScript Professional",
        issuer: "Udemy",
        date: "2022",
        credential_url: "#",
        image_url: null,
        skills: ["TypeScript", "Type Safety", "OOP"],
        featured: false,
        display_order: 3,
        created_at: new Date().toISOString(),
    },
];
